### ISSUE TITLE
PDD scans target folder when building on Rultor

### ISSUE THREAD

**Issue by carlosmiranda** [jcabi/jcabi-maven-skin#13]
See [this log](http://www.rultor.com/t/1603-70236344) from #12.

>ERROR: "there are 2 duplicate(s) of the same puzzle: src/it/basics/verify.groovy:68-70, target/it/basics/verify.groovy:68-70, while maximum 1 duplicate is allowed"
ERROR: "there are 2 duplicate(s) of the same puzzle: src/it/basics/verify.groovy:77-80, target/it/basics/verify.groovy:77-80, while maximum 1 duplicate is allowed"

Rultor scans both `src/` and `target/`, which means any puzzle will appear twice for files that are be copied over (such as XML files or Groovy scripts). This causes the build to fail. To fix this, we need to add `mvn clean` in `.rultor.yml`'s `merge` script, right before the `pdd` command is invoked.

**Comment by maurezen** [comment]
@yegor256 @dmarkov any comments? this issue is a blocker.

**Comment by maurezen** [comment]
@yegor256 @dmarkov gentlemen?

**Comment by carlosmiranda** [comment]
@yegor256 We need your help here in updating `.rultor.yml`.

**Comment by yegor256** [comment]
@carlosmiranda fixed

**Comment by carlosmiranda** [comment]
@yegor256 Thanks, will close it as soon as payment is made.

**Comment by dmarkov** [comment]
@oruam85 the issue is yours, please help

**Comment by yegor256** [comment]
@dmarkov assign me to this task, moreover I fixed it already

**Comment by dmarkov** [comment]
@carlosmiranda thanks for reporting! I topped your account for 15 mins, transaction 50519775

**Comment by oruam85** [comment]
@dmarkov  i believe that @yegor256 has fixed this bug.

**Comment by yegor256** [comment]
@carlosmiranda please close, it's fixed

**Comment by carlosmiranda** [comment]
@yegor256 Yes, thank you! Closing...

**Comment by dmarkov** [comment]
> @dmarkov assign me to this task, moreover I fixed it already

@yegor256 OK, it's yours, please proceed

**Comment by dmarkov** [comment]
@yegor256 thanks, paid, **30 mins** to your account, payment ID is `000-503a6f17`. +30 added to your rating, at the moment it is: [+5438](http://www.netbout.com/b/35008?open=rating)

**Comment by maurezen** [comment]
@yegor256 a question here, if I may, since I'm a bit confused by the process.

You seem to have committed directly to `master` here, yet it is stated that `master` is read-only, etc, etc. How does that work?

**Comment by yegor256** [comment]
@maurezen sometimes I cut corners and commit to master. not a good practice, but in very simple cases  I do this.
