### ISSUE TITLE
Missing information about additional dependencies

### ISSUE THREAD

**Issue by krzyk** [jcabi/jcabi-maven-skin#14]
README.md doesn't contain information that to build this project one has to have ruby gem `fontcustom` installed:
``
[ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.3:exec (fontcustom) on project jcabi-maven-skin: Command execution failed. Cannot run program "fontcustom" (in directory "/tmp/jcabi-maven-skin/target"): error=2, No such file or directory -> [Help 1]
``
One has to look into `.rultor.yml` file to find it.

**Comment by dmarkov** [comment]
this task will get someone's attention soon

**Comment by dmarkov** [comment]
@jenya this task is yours, please help (see our key [principles of work](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html)). If you have any technical questions, don't hesitate to ask right here... The budget here is **30 mins**, which is exactly how much time will be paid for, when the task is [completed](http://www.xdsd.org/2014/04/15/definition-of-done.html)

**Comment by dmarkov** [comment]
@krzyk thanks for the report, I topped your acc for 15 mins, payment ID `50518842`

**Comment by dmarkov** [comment]
@apocarteres it's yours, please go ahead

**Comment by apocarteres** [comment]
@dmarkov it's blocked by https://github.com/jcabi/jcabi-maven-skin/issues/18

**Comment by apocarteres** [comment]
@dmarkov please find the reviewer for PR https://github.com/jcabi/jcabi-maven-skin/pull/19

**Comment by apocarteres** [comment]
@krzyk as it turned out it's already added to README.md. please confirm

**Comment by krzyk** [comment]
yes it is

**Comment by dmarkov** [comment]
@apocarteres Thanks so much! Your account was topped up for **30 mins** (transaction ID is `51519044`)... added +30 to your rating, now it is equal to [+225](http://www.netbout.com/b/35111?open=rating)
