### ISSUE TITLE
Question about #16

### ISSUE THREAD

**Issue by apocarteres** [jcabi/jcabi-maven-skin#20]
@yegor256 Hi, Yegor. I have several questions regarding puzzle #16 

Basically, puzzle #16 is about issue in template engine which is being used to generated site for <code>jcabi-maven-plugin</code>.
The problem is that it generates for <pre> <<< >>> </pre> tag obsolete <code>tt</code> tag. Yes it does. But what's needed exactly in terms of this puzzle? 

I assume that it would be 2 steps:

1. Fix validator
<pre>
MatcherAssert.assertThat(
    htmlResponse.valid(),
    Matchers.describedAs(htmlResponse.toString(), Matchers.is(true))
)
</pre>

2. Do something with <code>.*apt.vm </code> files? Remove/replace <pre> <<< >>> </pre> tag? Something else?

**Comment by YamStranger** [comment]
@yegor256 please provide additional info here

**Comment by dmarkov** [comment]
@yegor256 please dispatch this issue

**Comment by amihaiemil** [comment]
@apocarteres Please close this issue. It was opened for issue #16, which is solved and "waits" for this to be closed.

**Comment by apocarteres** [comment]
@amihaiemil sure. thx
