### ISSUE TITLE
EOF for files

### ISSUE THREAD

**Issue by YamStranger** [jcabi/jcabi-maven-skin#24]
as @dpisarenko commented on Jan 24 under "verify.groovy:68-70: This validation doesn't work because... #16." There is some problem that can be fixed by adding .attributes to this project to set EOF to all files as at Linux (it is for successful run "mvn clean install -Pqulice") for git repository.

**Comment by YamStranger** [comment]
@dmarkov is this valid issue?

**Comment by dmarkov** [comment]
@yegor256 please pay attention to this issue

**Comment by yegor256** [comment]
@YamStranger fixed in https://github.com/jcabi/jcabi-maven-skin/commit/7aa468923cd34e4a8b612404a39fd9133abe1098
