### ISSUE TITLE
Copyright section is outdated

### ISSUE THREAD

**Issue by maurezen** [jcabi/jcabi-maven-skin#8]
Copyright sections still feature 2014 as a year.

**Comment by dmarkov** [comment]
I'll ask someone to take care of this task soon

**Comment by dmarkov** [comment]
@romankisilenko the task is for you now, follow [these guidelines](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html). Don't hesitate to ask any technical questions right here. This task's budget is **30 mins**. This is exactly how much will be paid when the problem explained above is solved. See [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) for more information

**Comment by dmarkov** [comment]
@maurezen many thanks, **15 mins** added to your acc for reporting this bug, pmt ID `50044617`

**Comment by RomanKisilenko** [comment]
@maurezen PR was reviewed and closed, please close this issue.

**Comment by dmarkov** [comment]
@romankisilenko Many thanks! **30 mins** were added to your account in Transaction ID `50614577`. +30 added to your rating, current score is: +180
